{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.2",
    "title": "Goosetrack project (group 1) backend V1 API docs",
    "description": "API documentation for GoIT Goosetrack project (group 1)",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },

  "consumes": ["application/json"],
  "produces": ["application/json"],

  "servers": [
    { "url": "https://goosetrack-18hi.onrender.com/api/v1" },
    { "url": "https://localhost:3001/api/v1" }
  ],

  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "Reviews",
      "description": "Reviews endpoints"
    },
    {
      "name": "Tasks",
      "description": "Tasks endpoints"
    }
  ],

  "paths": {
    "/users/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "security": [],
        "requestBody": {
          "description": "Registration request body object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Succeed",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Validation failure",
            "content": {}
          },
          "409": {
            "description": "Email is in use",
            "content": {}
          }
        }
      }
    },

    "/users/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User authentication",
        "parameters": [],
        "security": [],
        "requestBody": {
          "description": "Login request body object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Logged in success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {}
          }
        }
      }
    },

    "/current": {
      "get": {
        "tags": ["Auth"],
        "summary": "Getting current user",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentUserResponse"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {}
          },
          "500": {
            "description": "Internal Server Error",
            "content": {}
          }
        }
      }
    },

    "/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "Logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Logged off succeed",
            "content": {}
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {}
          }
        }
      }
    },

    "/user": {
      "patch": {
        "tags": ["Auth"],
        "summary": "User update",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "User's update object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UserUpdateRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/UserUpdateRequest"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {}
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Name Surname"
          },
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "user@example.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },

      "RegistrationResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "number",
            "description": "Response status",
            "example": "200"
          },
          "message": {
            "type": "string",
            "description": "Response message",
            "example": "Success"
          },
          "user": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email",
                "example": "user@example.com"
              }
            }
          }
        },
        "example": {
          "status": 201,
          "message": "Success",
          "user": {
            "email": "user@example.com"
          }
        }
      },

      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "user@example.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },

      "LoginResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "number",
            "description": "Response status",
            "example": "200"
          },
          "message": {
            "type": "string",
            "description": "Response message",
            "example": "Success"
          },
          "user": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "format": "email"
              }
            }
          },
          "token": {
            "type": "string",
            "description": "User's token",
            "example": "String"
          }
        },
        "example": {
          "status": 200,
          "message": "Success",
          "user": {
            "email": "user@example.com"
          },
          "token": "string"
        }
      },

      "CurrentUserResponse": {
        "type": "object",
        "properties": {
          "status": {
            "type": "number",
            "description": "Response status",
            "example": "200"
          },
          "message": {
            "type": "string",
            "description": "Response message",
            "example": "Success"
          },
          "user": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "User's name",
                "example": "Name Surname"
              },
              "email": {
                "type": "string",
                "description": "User's email",
                "example": "user@example.com"
              },
              "avatarURL": {
                "type": "string",
                "description": "User's avatar url"
              },
              "phone": {
                "type": "string",
                "description": "User's phone number"
              },
              "skype": {
                "type": "string",
                "description": "User's skype"
              },
              "birthdate": {
                "type": "string",
                "description": "User's birthdate"
              },
              "role": {
                "type": "string",
                "description": "User's role"
              },
              "theme": {
                "type": "string",
                "description": "User's theme"
              },
              "createdAt": {
                "type": "string",
                "description": "Date of user creation"
              },
              "updatedAt": {
                "type": "string",
                "description": "Date of user update"
              }
            }
          }
        },
        "example": {
          "status": 200,
          "message": "Success",
          "user": {
            "name": "Name Surname",
            "email": "user@example.com",
            "avatarURL": "https://goosetrack-18hi.onrender.com/images/avatars/default.svg",
            "phone": "",
            "skype": "",
            "birthdate": "",
            "role": "user",
            "theme": "light",
            "createdAt": "2023-08-27T07:40:05.960Z",
            "updatedAt": "2023-08-27T09:30:34.756Z"
          }
        }
      },
      "securitySchemes": {
        "Bearer": {
          "type": "http",
          "scheme": "bearer",
          "bearerFormat": "JWT"
        }
      }
    }
  }
}
